### ISSUE TITLE
Font disappears on /platform website

### ISSUE THREAD

**Issue by ghost** [dashevo/wp-dash-theme#90] opened 2021-03-11 13:02 UTC
When scrolling down the page with a Logitech mouse in "Free scroll" mode (no-resistance, pretty popular) the font on some rows disappear. I tested this on Chrome and Firefox. Without the "Free-Scroll" mode it did behave normally and not disappear. I attach example images.
![plat-website](https://user-images.githubusercontent.com/60034953/110790896-e03de480-8271-11eb-9d55-e84e593b2bd2.png)
![plat-website2](https://user-images.githubusercontent.com/60034953/110791277-4fb3d400-8272-11eb-9db7-52532d80a2ba.png)

**Comment by ktechmidas** [comment] 2022-08-29 04:55
Hey there! 

Unfortunately we cannot reproduce this easily so I'm going to close this issue for now, if you or anyone else has a step-by-step guide to reproduce this error we will look into it further. Also some details about the operating system/device/etc it's happening on would be greatly helpful in getting to the bottom of this.

**Closed by ktechmidas** 2022-08-29 04:55 UTC
